/** Descendant directories skipped by broad filesystem inspection tools. */
export const HARD_EXCLUDED_DIRS: readonly string[] = [
  ".git",
  ".worktrees",
  ".svn",
  ".hg",
  ".bzr",
  "node_modules",
  ".venv",
  "venv",
  ".tox",
  "__pycache__",
  ".mypy_cache",
  ".pytest_cache",
  ".cache",
  ".next",
  "target",
  "dist",
  "build",
  "dosdevices",
  "pfx",
  "wineprefix",
  "lost+found",
];
